server:
  port: 9991

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backcli?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.yi.backcli.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      yi:
        backcli:
          dao: debug